### ISSUE TITLE
How to use cursorMark to sort the src records for copy.

### ISSUE THREAD

**Issue by beiyehou** [jasonpanacea/SolrCopier#1]
When traversing the index you should use a cursor rather then the start and rows parameters. Check this description of the use of cursorMark: http://solr.pl/en/2014/03/10/solr-4-7-efficient-deep-paging/

**Comment by beiyehou** [comment]
https://github.com/solariumphp/solarium/issues/345
https://github.com/solariumphp/solarium/pull/421

**Comment by jasonpanacea** [comment]
added selectSortByPageWithCursorMark
